# Generated by Django 5.0.2 on 2025-01-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_executiveleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='prefects/')),
            ],
        ),
    ]
