# Generated by Django 5.0.2 on 2025-01-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_prefect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='staff/')),
                ('category', models.CharField(choices=[('staff', 'Staff'), ('non_staff', 'Non-Staff')], default='non_staff', max_length=10)),
            ],
        ),
    ]
