# Generated by Django 5.0.2 on 2025-01-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_galleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='SchoolGallery',
        ),
    ]
