# Generated by Django 5.0.2 on 2025-01-31 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_remove_unebperformance_uace_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uaceperformance',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='uaceperformance',
            name='principal_passes',
        ),
        migrations.RemoveField(
            model_name='uaceperformance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='uaceperformance',
            name='subsidiary_passes',
        ),
        migrations.RemoveField(
            model_name='uceperformance',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='uceperformance',
            name='distinctions',
        ),
        migrations.RemoveField(
            model_name='uceperformance',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='uceperformance',
            name='subject',
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='one_principal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='subsidiaries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='three_principals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='two_principals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uaceperformance',
            name='uneb_performance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uace_performance', to='schoolapp.unebperformance'),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='first_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='fourth_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='second_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='third_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uceperformance',
            name='uneb_performance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uce_performance', to='schoolapp.unebperformance'),
        ),
        migrations.AlterField(
            model_name='unebperformance',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
